url: https://thetanewzealand.github.io/

collections:
  about:
    output: true
  programmes:
    output: true
  resources:
    output: true
  student-resources:
    output: true
  teacher-resources:
    output: true
  whanau-resources:
    output: true
  accordion-student-resources:
    output: true
  accordion-teacher-resources:
    output: true
  accordion-whanau-resources:
    output: true
